### ISSUE TITLE
[Question] Why are you returning pointers in the matrix response. 

### ISSUE THREAD

**Issue by gwuah** [AirspaceTechnologies/go-mapbox#4]
First off, nice library. I love the implementation.
But i'm wondering why you returning pointers to the durations and distances instead of raw floats?
Is there a specific reason? 
(I'm quite new to golang so i'm just trying to understand if there's an advantage to doing that.)

**Comment by jose-airspace** [comment]
@gwuah great question, I know its usually to handle nil when marshaling but it seems weird that the values in the array would be nil. I think @tsaifi9 might be able to answer definitely though

**Comment by jclinford** [comment]
@gwuah Mapbox will return null when the duration or distance is invalid or cannot be found. So we need pointers to distinguish from a true 0 distance (e.g. [i] and [j] are the exact same location) and an invalid/not found distance (e.g. [i] -> [j] tries to drive over an ocean where no route exists)


https://docs.mapbox.com/api/navigation/#matrix
> Durations as an array of arrays that represent the matrix in row-major order. durations[i][j] gives the travel time from the ith source to the jth destination. All values are in seconds. The duration between the same coordinate is always 0. If a duration cannot be found, the result is null.

**Comment by gwuah** [comment]
ahh oh okay. Thanks for the answer guys!
