### ISSUE TITLE
Add a way to set a Referer to support URL restriction

### ISSUE THREAD

**Issue by oliverpool** [AirspaceTechnologies/go-mapbox#7]
Mapbox supports restricting the URLs allowed to query the API: https://docs.mapbox.com/accounts/guides/tokens/#url-restrictions

When enabled, no API call can be made using this package.

It would be great to be able to set a `Referer` header an all requests.

For instance adding a `Referer` field to the `Client` struct and adding the header on `Client.do` if set (I can submit a PR if you wish).

**Comment by oliverpool** [comment]
I would be willing to make a PR, if you think this is a good idea 😊

**Comment by jclinford** [comment]
Sorry @oliverpool just now saw this - We don't have a use case on our side, but yes feel free to create a PR and we would be happy to merge that in.

**Comment by oliverpool** [comment]
Code is ready: https://github.com/AirspaceTechnologies/go-mapbox/compare/master...oliverpool:client_referer?expand=1

But I built it on top of the PR #9, so it has to wait for the PR 9 to be merged first :)

**Comment by oliverpool** [comment]
Thank you for the quick review and the merges!
